### PR TITLE
fix(F-D17): missing Divide-by-Zero Check in OpUrem32Reg

### LINKED ISSUE #127: [F-D17] Missing Divide-by-Zero Check in OpUrem32Reg
## Summary

The SBPF interpreter's `OpUrem32Reg` instruction handler is missing a divide-by-zero check, causing a Go runtime panic instead of returning the proper `ExcDivideByZero` error when the source register contains zero.

## Root Cause

In `pkg/sbpf/interpreter.go`, the `OpUrem32Reg` case directly performs the modulo operation without first checking if the divisor (source register value) is zero:

```go
case OpUrem32Reg:
    if !ip.sbpfVersion.EnablePqr() {
        err = ExcInvalidInstr
        break
    }
    r[ins.Dst()] = uint64(uint32(r[ins.Dst()]) % uint32(r[ins.Src()]))  // No zero check!
    pc++
```

This causes a Go runtime panic (`integer divide by zero`) when `r[ins.Src()]` is zero.

Other similar register-based division/modulo operations correctly check for zero before performing the operation. For example, `OpUrem64Reg`:

```go
case OpUrem64Reg:
    if !ip.sbpfVersion.EnablePqr() {
        err = ExcInvalidInstr
        break
    }
    if src := r[ins.Src()]; src != 0 {
        r[ins.Dst()] %= r[ins.Src()]
    } else {
        err = ExcDivideByZero
    }
    pc++
```

## Impact

- **Runtime Panic**: The missing check causes a Go runtime panic that crashes the entire process
- **Differential Fuzzing Failure**: Agave correctly returns `DivideByZero` error (error code 5), while Mithril panics
- **Denial of Service**: A malicious program could intentionally trigger this panic to crash the validator

## Fix

Modified `pkg/sbpf/interpreter.go` to add the divide-by-zero check:

```go
case OpUrem32Reg:
    if !ip.sbpfVersion.EnablePqr() {
        err = ExcInvalidInstr
        break
    }
    // === START RV FIX ===
    if src := uint32(r[ins.Src()]); src != 0 {
        r[ins.Dst()] = uint64(uint32(r[ins.Dst()]) % src)
    } else {
        err = ExcDivideByZero
    }
    // === END RV FIX ===
    pc++
```

## Files Modified

- `pkg/sbpf/interpreter.go` (modified)

### PR DESCRIPTION
**Pull request by sonicfromnewyoke**
### Problem

The SBPF interpreter's `OpUrem32Reg` instruction handler is missing a divide-by-zero check, causing a Go runtime panic instead of returning the proper` ExcDivideByZero` error when the source register contains zero.

### Summary of Changes

- changed error text to be the same as `DivideByZero` error of original `sbpf` returns
- added check with returning `DivideByZero` error

closes #127 

cc @smcio

### CODE REVIEW

File: pkg/sbpf/interpreter.go [hunk 1]
```diff
@@ -488,7 +488,11 @@ mainLoop:
 				err = ExcInvalidInstr
 				break
 			}
-			r[ins.Dst()] = uint64(uint32(r[ins.Dst()]) % uint32(r[ins.Src()]))
+			if src := r[ins.Src()]; src != 0 {
+				r[ins.Dst()] = uint64(r[ins.Dst()] % src)
```
Comment (juliankuners) [inline pkg/sbpf/interpreter.go:492]: `src` is not casted to uint32 to here, while registers in `r` are uint64. The module operation also emits the cast to uint32.

This differs from Agaves (solana-sbpf) implementation, see `solana-sbpf:src/interpreter.rs`:
```
ebpf::UREM32_REG if self.executable.get_sbpf_version().enable_pqr() => {
    throw_error!(DivideByZero; self, self.reg[src], u32);
                    self.reg[dst] = (self.reg[dst] as u32 % self.reg[src] as u32) as u64;
},
```
and `throw_error` macro here (specifically, case 2):
```
macro_rules! throw_error {
    ($self:expr, $err:expr) => {{
        $self.vm.registers[11] = $self.reg[11];
        $self.vm.program_result = ProgramResult::Err($err);
        return false;
    }};
    (DivideByZero; $self:expr, $src:expr, $ty:ty) => {
        if $src as $ty == 0 {
            throw_error!($self, EbpfError::DivideByZero);
        }
    };
    (DivideOverflow; $self:expr, $src:expr, $dst:expr, $ty:ty) => {
        if $dst as $ty == <$ty>::MIN && $src as $ty == -1 {
            throw_error!($self, EbpfError::DivideOverflow);
        }
    };
}
```
